go.mod, trusted_applet/main.go, trusted_applet/net.go, trusted_applet/ssh.go
- Ensure we tell the user-provided function to exit, and wait for it to do so before ripping out old network config.
- Make SSH server close connections when network config changes.
- Factor out network configuration bits for better readability.
=> Improve DHCP hook reliability

Makefile, trusted_applet/bee.go, trusted_applet/mem_bee.go
This commit supports [amored-witness-boot PR #12](https://github.com/transparency-dev/armored-witness-boot/pull/12) by adding optional compile time flags to support BEE aliased regions.
=> support BEE relocation

trusted_applet/main.go
- return errors from `runWithNetworking` rather than bomb out
- run `omniwitness.Main` inline
=> Omni tweaks

trusted_applet/internal/storage/internal.go, trusted_applet/internal/storage/slots/journal.go, trusted_applet/internal/storage/slots/journal_test.go, trusted_applet/internal/storage/slots/slots.go, trusted_applet/internal/storage/slots/slots_test.go, trusted_applet/internal/storage/testonly/memdev.go
Previously, the entire journal would be re-scanned from the beginning in order to verify that writing a new entry was successful. Depending on the size of the journal/number of entries it contains, this could take a while.
This PR improves that by only re-reading the written entry.
=> Only re-read the entry which was just written

README.md
Currently errors with `signify-openbsd: please use naming scheme of keyname.pub and keyname.sec`.
=> Fix signify key generation command.

go.mod, go.sum, third_party/dhcp/client.go, third_party/dhcp/dhcp.go, trusted_applet/main.go, trusted_applet/net.go
- Update to recent gVisor
- Bump imx-enet, which has been updated to a recent gVisor
- Fixup a number of breaking gVisor API changes, e.g.:
- `bufferv2` has gone, so rework onto `buffer`
- types which were aliases of `[]byte` are now structs
=> Bump gVisor to v0.0.0-20230614190805-57027c7d31f8

go.mod, go.sum, trusted_applet/main.go, trusted_applet/net.go
This seems like a nice solution to building-in a maintained set of TLS roots for our TLS client requests: it's reproducible, and dependabot should help us keep this fresh.
These roots are taken from the Mozilla root programme (see the tool which generates the bundle here: https://cs.opensource.google/go/x/crypto/+/183630ad:x509roots/gen_fallback_bundle.go;l=67)
=> Use Go fallback TLS roots

api/example_firmware_release.json, api/log_entries.go, api/log_entries_test.go
This is used as the leaf in the binary transparency log. This is the other side of PR #69.
=> API struct to represent the firmware manifest

cloudbuild.yaml
Callouts to a few things proposed in this PR:
* Origin: `transparency.dev/armored-witness/binary_transparency/0`
* Example Claimant Model statement (TAG_NAME is blank in development, should not be in production):
[firmware-log-sequence_applet_log_entry.txt](https://github.com/transparency-dev/armored-witness-applet/files/12163933/firmware-log-sequence_applet_log_entry.txt)
The output of the digest from `sha256sum` includes the filename as well, thinking of stripping that (but would need to add a field to indicate what this is, e.g. trust_applet, trusted_os)?
=> Add write to transparency log after building and signing.

trusted_applet/internal/update/rpc/update_client.go
This is mainly just to make it easier to test the parent package (`go test` fails currently due to tamago deps).
=> Move RPC update client out into its own package

trusted_applet/internal/update/mock_update_test.go, trusted_applet/internal/update/update.go, trusted_applet/internal/update/update_test.go
Reboot is now performed immediately on successful OS/Applet install and the separate call to Reboot is no longer required.
=> Clarify reboot semantics

Dockerfile, Makefile
This PR:
- Adds support for managing a local serverless log instance for local testing.
- Creates a manifest file whenever the applet is built
To use the log, append a `log_applet` target to the make invocation, e.g.:
```
make trusted_applet log_applet
```
Note that `LOG_PUBLIC_KEY` and `LOG_PRIVATE_KEY` env variables are expected to be set to paths to key files, in keeping with the other key-related env vars.
=> Add makefile targets for managing local dev FT log

trusted_applet/internal/firmware/verify.go
This checks that:
1. The Checkpoint is from the correct log
2. The firmware manifest is committed to by the Checkpoint
3. The manifest commits to the firmware executable
Future work would add witnessing checks to this, but we need to think
through the bootstrapping process before doing this.
=> Verifier for firmware

Makefile, go.mod, go.sum
Migrate to new `manifest` tool location, and specify firmware type.
Needs transparency-dev/armored-witness/pull/17
=> Bump manifest tool and add firmware_type flag

release/cloudbuild.yaml, release/cloudbuild_ci.yaml
Naming layout will look like:
* `armored-witness-firmware[-ci]/[trusted-applet, trusted-os, boot, recovery]/<tag_name>/elf, manifest`
* `armored-witness-firmware-log[-ci]/...`
Tested cloudbuild_ci.yaml on the `dev-trigger` in our project.
=> Write to a single bucket for the Trusted Applet artifacts.

.github/workflows/pr_build.yml, Makefile
This PR uses transparency-dev/armored-witness#21 to start the process of switching over to using signed manifests rather than signatures on applet binaries.
Note that with this PR, the file referenced by the `$APPLET_PRIVATE_KEY` must now contain a `Note` compatible verifier string.
=> Create signed manifest

Makefile
This PR ensures that there is a vaguely sensible defined ordering for local dev builds by using unix epoch seconds as the patch version.
=> Make dev SemVer use epoch

Makefile, go.mod, go.sum, release/cloudbuild.yaml, release/cloudbuild_ci.yaml
This PR updates the Makefile and cloudbuild configs to store the applet firmware binary in the correct CAS location.
See https://github.com/transparency-dev/armored-witness-common/pull/15
=> Store firmware binaries in CAS

.github/workflows/pr_build.yml, Makefile, release/cloudbuild.yaml, release/cloudbuild_ci.yaml
This PR bumps the version of TamaGo used to build and test to 1.21.3 (required due to recent changes to support BEE), and adds a check to the Makefile to ensure that a TamaGo version at least this new is always used to compile binaries.
=> Bump to TamaGo v1.21.3

release/cloudbuild_ci.yaml
Compare:
- curl -i https://storage.googleapis.com/armored-witness-firmware-log-ci/checkpoint
- curl -i https://storage.mtls.cloud.google.com/armored-witness-firmware-log-ci/checkpoint
In addition, I think these URLs should be added to the manifest file. This makes it easy for the verifier to set these build flags, even if they change over time. It also provides assurance that all users are receiving updates from the same logs.
=> Use URL that works unauthenticated for the public artifacts

Makefile, trusted_applet/main.go
This information isn't useful and makes it hard to reproducibly build the same output. If it was still useful then we could add it to the manifest, but it isn't, and so it is being removed. The build epcoh that is merged into CI builds will also need consideration, but is a separate PR.
=> Don't embed build info

release/cloudbuild.yaml, release/cloudbuild_ci.yaml
This PR updates GCB configs for the newly rolled CI log.
See also:
- https://github.com/transparency-dev/armored-witness/pull/67
- https://github.com/transparency-dev/armored-witness-os/pull/117
=> Roll applet logs

release/cloudbuild.yaml, release/cloudbuild_ci.yaml
This fixes the problem that objects uploaded to `entriesDir` are not deleted.
=> Use per Cloud Build trigger unique entriesDir for sequencing.

go.mod, go.sum, trusted_applet/internal/update/rpc/update_client.go
This PR causes the applet to use the [new chunked update](https://github.com/transparency-dev/armored-witness-os/pull/130) support when installing applet or OS updates.
=> Send chunked firmware updates

.github/workflows/pr_build.yml, Makefile, go.mod, go.sum, release/cloudbuild.yaml, release/cloudbuild_ci.yaml, release/cloudbuild_presubmit.yaml
There are some important TamaGo fixes in 1.21.5, this PR makes that the minimum version.
See also: 
- transparency-dev/armored-witness-os/pull/135
- transparency-dev/armored-witness-boot/pull/57
=> Bump TamaGo-go version to 1.21.5 for Applet

release/cloudbuild_ci.yaml
This was downgraded from 0.2.X to 0.0.X because it seemed arbitrary. This caused a latent problem that has now come to light as we're trying to flash these CI builds onto the devices, which is that recent builds appear older than those from before the version downgrade. In the interests of being pragmatic, bumping this version to a newer version bypasses this problem. We can reset this to 0.0.X again should we ever rotate the CI logs.
=> Bump CI version to 0.3.X

trusted_applet/update.go
This makes it clearer whether context timeouts are while trying to make the request, or while downloading the data.
=> Include more info in returned errors during update

trusted_applet/update.go
Also removed the pretence of supporting a 0 timeout, this doesn't work because of the context.WithTimeout at the top of the method.
=> Use same timeout (30s) as set in net.go

trusted_applet/update.go
This broke the nil error condition. Because all other error returns are decorated, a bare error from this method can be inferred to have come from io.ReadAll
=> Revert silly error where error would always be returned

go.mod, go.sum, trusted_applet/net.go
This PR:
- bumps `tamago` to dfe6a899d3a7804c0a5bd77aecdb38851871e1f5
- bumps `imx-enet` to 5f2c2e71410a0e0d500f3ff3b6b0887a074934a3
- follows API changes in `imx-enet` to pass in a `Stack`
=> Bump tamago & imx-enet

go.mod, go.sum, trusted_applet/update.go
Bumps `common` to `835b60b7c617c69dc26e9b209f59cc1ae2d75a96` and updates the `binFetcher` signature to match the new version.
=> Update binFetcher signature

release/cloudbuild_ci.yaml
This fixes the current problem, which is that they are trying to distribute to prod. I don't like that the URL will be api.transparency.dev/distributor-ci/distributor/v0/... but deduplicating that will require a lot more work throughout the omniwitness codebase.
=> Make the CI witnesses distribute to CI distributor

release/cloudbuild.yaml, release/cloudbuild_ci.yaml
Any of these values could be rotated in the future, and given they are critical for reproducible builds they should be in the manifest. One could argue that these should have their own top-level named entry in the manifest rather than being buried in build_envs. For pragmatism, let's use this approach for now and we can revisit this in a month as part of a whole manifest refactor before we commit to v1.
=> Commit to all build envs in manifest

go.mod, go.sum, trusted_applet/net.go
Previously this was making a DNS query for every request. Given that we have a very small number of DNS lookups that we make, and we git them relatively frequently, a cache cuts down on the load we put on the DNS server, and the latency involved in waiting for it before each request.
=> Cache DNS responses for a minute

trusted_applet/update.go
This PR ensures there's always a trailing slash on either of the FT log related URLs.
This fixes a sharp edge, as failing to include the trailing slash in a base URL (e.g. in build-time constants in the applet) will cause the last element in the URL path to silently be dropped.
e.g. https://go.dev/play/p/8jJwNUsmVOz
=> Ensure we don't lose trailing part of prefix

trusted_applet/main.go
Force `runtime.CallOnG0` symbol to be present in the symtab so we can invoke it from the OS in the event of a segfault.
=> Add CallOnG0 symbol for inspect

third_party/dhcp/client.go, third_party/dhcp/dhcp.go, third_party/dhcp/dhcp_string.go, trusted_applet/main.go, trusted_applet/net.go
This PR improves quality of life for folks running a witness on their network a bit.
With this change, the AW:
- sends a stable `ClientID` (`AW-<serial>`) to the DHCP server, allowing the server to be configured with a specific set of values to return (you can generally do the same with MAC addresses, but this is a bit friendlier),
- sends a requested `hostname` (a sanitised version of the witness identity name, e.g. `dev-armoredwitness-proud-meadow`)
=> Allow AW to specify a stable ID and hostname for DHCP

trusted_applet/main.go
On large NTP changes the applet aborts with static networking, this prevents that.
=> avoid applet exit on static networking restart

go.mod, go.sum, trusted_applet/key.go, trusted_applet/main.go
This PR derives a new key to be used to authenticate the witness to a Bastion host.
I've done some refactoring to simplify/reuse code where possible to avoid mistakes in the future.
Key derivation results remain the same with the refactoring:
Before 
```
----------------------------------------------------------- Trusted OS ----
Serial number ..............: 720A9DEAD4391E1E
Secure Boot ................: false
SRK hash ...................:
Revision ...................: a2c259b
Version ....................: 0.1.2-11-ga2c259b
Runtime ....................: go1.22.0 tamago/arm
Link .......................: false
MAC ........................: c6:08:a0:62:04:44
IdentityCounter ............: 0
Witness/Identity ...........: DEV:ArmoredWitness-misty-snow+4235d37b+ATQcX3zXpdLJdudAP97VhTkO4m0DEyld9nd …
```
=> Derive BastionID

trusted_applet/main.go
This PR adds a local admin `/status` HTTP endpoint to make it a little easier for custodians to fetch this info from running devices.
```bash
$ curl -i http://10.0.0.1:8081/status
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Wed, 12 Jun 2024 18:06:41 GMT
Content-Length: 1408
----------------------------------------------------------- Trusted OS ----
Serial number ..............: 720A9DEAD4391E1E
Secure Boot ................: false
SRK hash ...................:
Revision ...................: d8827e6
Version ....................: 0.1.2-21-gd8827e6
Runtime ....................: go1.22.0 tamago/arm
Link .......................: true
MAC ........................: c6:08:a0:62:04:44
IdentityCounter ............: 0
Witness/Identity ...........: …
```
=> Add status HTTP endpoint

go.mod, go.sum, trusted_applet/main.go
This PR enables the bastion feeder rate limit support in the AW applet.
```
I0625 14:48:52.012078   55749 main.go:148] (77ms/77ms) transparency.dev/armored-witness/firmware_transparency/ci/2: 429 Too Many Requests:
I0625 14:48:52.012106   55749 main.go:148] (77ms/77ms) transparency.dev/armored-witness/firmware_transparency/prod/1: 429 Too Many Requests:
I0625 14:48:52.012172   55749 main.go:148] (79ms/79ms) Armory Drive Prod 2: 429 Too Many Requests:
I0625 14:48:52.012274   55749 main.go:148] (79ms/79ms) transparency.dev/armored-witness/firmware_transparency/ci/3: 200 OK: — DEV:ArmoredWitness-misty-snow TrDK0riwemYAAAAA6+PfIdN88T6c/rNnxeWYiE5lXUP65wmdOQX6yF93VPM7t8psf1/S9NcOMygfqUkonWHVdumdEgg7WIOPmhDoAw==
I0625 14:48:52.015356   55749 main.go:148] (54ms/54ms) go.sum database tree: 429 …
```
=> Wire up bastion rate limit

.github/workflows/pr_build.yml, Makefile, go.mod
This PR bumps the minimum Tamago version to 1.22.4, in line with transparency-dev/armored-witness-os#259.
Needs transparency-dev/armored-witness#264 for presubmit.
=> Bump Tamago to 1.22.4

go.mod, go.sum
This will make the witness distribute to all known logs now, not just those with a feeder.
=> Bumped witness to 64080cc

go.mod, go.sum
This brings in transparency-dev/witness#293 which improves bastion connection resilience.
=> Bump witness to 1b7aedbc4a2b8319d1a86e0d47b19d0087bf4957

go.mod, go.sum
This PR bumps the `transparency-dev/witness` dep to `2141e0e43f896d5ec9af9f6312b660ea343c330d
` in order to pull in transparency-dev/witness#325 which fixes issues with [C2SP tlog-witness](https://c2sp.org/tlog-witness) spec compliance.
=> Bump witness to 2141e0e43f896d5ec9af9f6312b660ea343c330d

trusted_applet/main.go
With a cosignature/v2 spec on the horizon (https://github.com/C2SP/C2SP/pull/146/), I'm cleaning out the old legacy signatures. I can't see any users of these any more.
=> Drop support for legacy witness sigs
