- trusted_applet/main.go
- trusted_applet/net.go
Make changes in applet network configuration flow corresponding to https://github.com/transparency-dev/armored-witness-os/pull/7
> Update applet to match protobuf config scheme

- .github/workflows/pr_build.yml
- Pin actions
- Reduce permissions
> Tighten pr_build.yml

- go.mod
- go.sum
- trusted_applet/net.go
Use the `DialContextTCP4` func added in https://github.com/usbarmory/imx-enet/pull/4
> Use the new DialContext func

- go.mod
- go.sum
- trusted_applet/main.go
- trusted_applet/net.go
Paired with https://github.com/transparency-dev/armored-witness-os/pull/21
> Use configured NTP server

- trusted_applet/main.go
This improves `runWithNetworking`'s handling of context expiring:
- Bail early if the context has been cancelled
This can happen in particular when NTP has just updated the system time, and DHCP is used to
configure the system's IP address; the sudden jump forward in time causes the DHCP lease to suddenly expire, which in turn causes the `ctx` here to become `Done`.
- Close mainListener when context expires
> runWithNetworking fixes

- .github/workflows/pr_build.yml
- go.mod
- go.sum
Brings `GoTEE` and `tamago` up-to-date.
> Bump Tamago-related deps

- api/log_entries.go
- trusted_applet/internal/update/fetch.go
- trusted_applet/internal/update/fetch_test.go
- trusted_applet/internal/update/http.go
This PR is of a lower readiness than usual, but submitting with the
known issues so that Al can use the serverless API to do the missing
work.
TODO:
> HTTP fetcher that implements the Remote interface

- Makefile
- trusted_applet/mem_bee.go
this PR fixes the ELF text start value to the correct BEE alias and adds missing stack offset linkage
> fix BEE memory layout

- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
Followup to https://github.com/transparency-dev/armored-witness/pull/17
> Specify firmware_type.

- Makefile
Match updated paths in transparency-dev/armored-witness-common#6
> Update applet artefact dir to match GCB

- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
This PR follows the recent changes to the `manifest` tool.
> Update GCB workflows with manifest changes

- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
Tested the CI config with the `dev-trigger`.
> Replace KMS signer with note signer.

- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
Followup to https://github.com/transparency-dev/serverless-log/pull/41
> Pass in KMS log key info for adding an applet entry to the the transparency log.

- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
Need to please the Cloud Build YAML parser.
> Reformat GCF --data string.

- trusted_applet/main.go
This PR addresses the situation where the update log isn't available at boot time.
Previously the error would cause the applet to exit, but now we'll retry.
> Don't fail if we can't talk to the update log at boot

- Dockerfile
- release/cloudbuild.yaml
- release/cloudbuild_ci.yaml
This supports reproducible builds
> Include build envs in manifest for Applet

- go.mod
- go.sum
> Update witness dependency

- trusted_applet/main.go
This reverts #246 and fixes #247
> Removed pprof

- trusted_applet/key.go
The applet currently derives a stable attestation key which is valid for the lifetime of the device, and uses this to convince us that (derived) witness identities were produced on-device.
transparency-dev/armored-witness/issues/253 will require a new "bastion backend" identity to be derived by the applet, and we'll need to ask custodians to let us know what this is for their particular device(s) - so these identifies must also be attested.
This PR factors out the creation of the attestation signer so that we can use it in a follow-up PR (https://github.com/transparency-dev/armored-witness-applet/pull/302) for the bastion backend key.
Towards transparency-dev/armored-witness/issues/253.
> Refactor to allow attesting to other things

- go.mod
- go.sum
This brings in:
- transparency-dev/witness#285
- transparency-dev/witness#283
> Bump witness to d1b22ee5e29f6e3c0474fd66150f0ee635a9ab8d

- go.mod
- go.sum
This PR pulls in transparency-dev/witness#290 to increase bastion burst.
> Bump witness to de182c8285043f6591fe425da067875ec737ee78

- .github/workflows/pr_build.yml
- Makefile
- go.mod
- go.sum
- trusted_applet/net.go
Tested on local h/w: OS1.24.6+Applet1.24.3 --> Applet1.24.6
> Bump to tamago-go1.24.6
